[global]
developmentMode = false

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#547BA3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"